# Generated by Django 3.2.13 on 2022-05-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.IntegerField(default=0)),
                ('formant', models.IntegerField(default=0)),
            ],
        ),
    ]
